[package]
name = "rpg_game"
version = "0.0.3"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
derive_builder = "0.20.2"
glam = "0.30.5"
hecs = "0.10.5"
noise = "0.9.0"
rand = "0.9.1"
sdl2 = { version = "0.37.0", features = ["gfx", "ttf"] }
